site_name: Vps Config
site_url: https://sabbirhassan.com/documentations/vps-config
nav:
  - Getting Started: getting_started.md
  - Install Network Time Protocol: ntp.md
  - Install Build Essentials: build_essentials.md
  - Edit Hosts and Hostname File: hostname.md
  - Customize Bash Prompt: customize_bash.md
  - Manage New User: new_user.md
  - Edit SSH Login Banner: login_banner.md
  - Configure SSH Daemon: csd.md
  - Configure Firewall: firewall.md
  - Configure Git: git.md
  - Manage SSL Certificates: certbot.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  logo: assets/icon/logo.svg
  favicon: assets/icon/logo.svg
  homepage: https://sabbirhassan.com/documentations/vps-config
  name: material
  features:
    - content.code.copy
    - content.code.line_numbers
    - content.code.annotation
    - navigation.sections
    - navigation.top
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/bitlaab
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/bitlaab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bitlaab
    - icon: fontawesome/brands/github
      link: https://github.com/bitlaab-bolt
copyright: Copyright © 2024 Sabbir Hassan™